# <center> Homework 1 </center>

# 0. Где мы сейчас?
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Jupyter_logo.svg/1200px-Jupyter_logo.svg.png" width="150">

[Jupyter Notebook](https://jupyter.org/) - интерактивная среда для запуска программного кода в браузере. Удобный инструмент для анализа данных, который используется многими специалистами по data science. Позволяет выполнять отдельные ячейки с кодом, а не всю программу сразу, что очень удобно при знакомстве с данными.

# 1. Python
> Python - это свободный интерпретируемый объектно-ориентированный расширяемый встраиваемый язык программирования очень высокого уровня 

>*(Г.Россум, Ф.Л.Дж.Дрейк, Д.С.Откидач "Язык программирования Python").*

А если без цитат, то питон - это просто очень крутой язык, созданный в 1991 году [Великодушным пожизненным диктатором](https://ru.wikipedia.org/wiki/%D0%92%D0%B5%D0%BB%D0%B8%D0%BA%D0%BE%D0%B4%D1%83%D1%88%D0%BD%D1%8B%D0%B9_%D0%BF%D0%BE%D0%B6%D0%B8%D0%B7%D0%BD%D0%B5%D0%BD%D0%BD%D1%8B%D0%B9_%D0%B4%D0%B8%D0%BA%D1%82%D0%B0%D1%82%D0%BE%D1%80) Гвидо ван Россумом и названный в честь любимого им шоу [Monty Python's Flying Circus](https://en.wikipedia.org/wiki/Monty_Python%27s_Flying_Circus)

<img src="https://advancelocal-adapter-image-uploads.s3.amazonaws.com/image.oregonlive.com/home/olive-media/width2048/img/tv/photo/2018/10/10/montycastjpg-7ef393e2355a42aa.jpg" width="300">

# 2. Anaconda

<img src="https://cdn-images-1.medium.com/max/1600/0*MVkCW8_Bmj-nuAnI.png" width="300">

[Сборка Anaconda](https://www.anaconda.com/products/individual) включает очень много полезных библиотек для анализа данных. 

Среди наиболее популярных библиотек:
 - <a href="http://numpy.org">Numpy</a> - это один из основных пакетов для математических вычислений. Он содержит средства для работы с многомерными массивами и высокоуровневыми математическими функциями
 - <a href="https://www.scipy.org/">SciPy</a> - научные вычисления. Методы оптимизации, интегрирования, модули обработки сигналов и изображений, статистика, линейная алгебра, сплайны, кластеризация и многое другое
 -  <a href="http://pandas.pydata.org/">Pandas</a> - основная библиотека для обработки и анализа данных. Предназначена для данных разной природы - матричных, панельных данных, временных рядов. Претендует на звание самого мощного и гибкого средства для анализа данных с открытым исходным кодом
 - <a href="http://scikit-learn.org/stable/">Scikit-learn</a> - реализация очень многих методов машинного обучения с отличной документацией. 
 - <a href="http://http://matplotlib.org/">matplotlib</a> - хорошая библиотека для визуализации данных

# 3. Задачки

## Задача 1
$N$ хоббитов делят $K$ кусков эльфийского хлеба поровну, не делящийся нацело остаток остается в корзинке у Сэма. Напишите функцию, которая принимает на вход параметры $N$ и $K$ и возвращает два числа: $x$ - cколько кусков эльфиского хлеба достанется каждому хоббиту, и $y$ - сколько кусков остаётся в корзинке.

In [1]:
def share_bread(N, K):
    # your code here
    x = K // N
    y = K % N
    return x, y

# если в функции всё верно, то после выполнения этой строчки, не должно выскакивать ошибок
assert share_bread(N=3, K=14) == (4, 2)

## Задача 2

В копях Мории хоббиты нашли стену, на которой высечены разные натуральные числа. Согласно древним сказаниям, это даты сражений. Хоббиты знают, что сражения происходили только по високосным годам. Помогите хоббитам определить, является ли год с данным числом датой великого сражения. Если это так, то верните строку "YOU SHALL PASS", иначе верните "YOU SHALL NOT PASS". Напомним, что в соответствии с хоббитским календарем, год является високосным, если его номер кратен 4, но не кратен 100, а также если он кратен 400.

In [2]:
def leap_year(year):
    # your code here
    TEXT_RESULT_TEMPLATE = 'YOU SHALL{}PASS'
    TEXT_RESULT_VARIANTS = {True: ' ', False: ' NOT '}
    
    bool_result = (year % 4 == 0) and (year % 100 != 0) and (year % 400 == 0)
    
    text_result = text_result = TEXT_RESULT_TEMPLATE.format(
        TEXT_RESULT_VARIANTS[bool_result]
    ) 
 
    return text_result

assert leap_year(5) == 'YOU SHALL NOT PASS'

## Задача 3
<img src="http://i0.kym-cdn.com/photos/images/original/001/187/255/5e9.gif" width=300>
Для могущественного магического ритуала Гендальфу необходимо быстро подсчитывать площадь своего амулета, который умеет менять размеры. Известно, что амулет имеет форму треугольника и Гендальф знает длину каждой из сторон. Напишите функцию, которая считает площадь амулета по трем сторонам.  

Подсказка: используйте формулу Герона
$$ S = \sqrt{p(p-a)(p-b)(p-c)} $$
$$ p = \frac{a + b + c}{2}$$


In [3]:
from math import sqrt

def amulet_area(a, b, c):
    # your code here
    p = (a + b + c) / 2
    
    S = sqrt(p * (p - a) * (p - b) * (p - c))
    
    return S

assert amulet_area(3, 4, 5) == 6

## Задача 4

Хоббиты собираются пешком идти до Мордора и им нужно подсчитать расстояние, которое им предстоит пройти. Хоббиты смогли вспомнить сразу несколько метрик расстояния: евклидово, манхэттена и косинусное, так что ваша задача - напистаь функцию под каждую из них. Важное условие - используйте только базовые функции numpy для решения.


* Евклидово расстояние
$$ d(a, b) = \sqrt{\sum_i (a_i - b_i)^2} $$
* Расстояние Манхэттена
$$ d(a, b) = \sum_i |a_i - b_i| $$
* Косинусное расстояние
$$ d(a, b) = 1 - \frac{a^\top b}{||a||_2\cdot||b||_2}$$

In [4]:
import numpy as np
import math


def cal_euclidean(a, b):    
    ## Your code here
    # distance = math.sqrt(sum((a - b) ** 2))
    distance = math.sqrt(sum([(comp_a - comp_b) ** 2 for comp_a, comp_b in zip(a, b)]))
    
    return distance

def cal_manhattan(a, b):    
    ## Your code here
    # distance = sum(abs(a - b))
    distance = sum([abs(comp_a - comp_b) for comp_a, comp_b in zip(a, b)])
    
    return distance

def cal_cosine(a, b):    
    ## Your code here
    # scalar_mul_a_b = sum(a * b)
    scalar_mul_a_b = sum([(comp_a * comp_b) for comp_a, comp_b in zip(a, b)])
    
    # norm_a = math.sqrt(sum(a * a))
    norm_a = math.sqrt(sum([comp_a ** 2 for comp_a in a]))
    # norm_b = math.sqrt(sum(b * b))
    norm_b = math.sqrt(sum([comp_b ** 2 for comp_b in b]))
    
    distance = 1 - (scalar_mul_a_b / (norm_a * norm_b))
    
    return distance

In [9]:
a = np.random.randint(-10, 10, size=10)
b = np.random.randint(-10, 10, size=10)
print(cal_euclidean(a, b))
print(cal_manhattan(a, b))
print(cal_cosine(a, b))

26.664583251946766
67
0.967248303264635


## Задача 5

Ну и напоследок, еще немного практики numpy, без которой не обходится ни один хоббит.


Создайте случайный array (`np.random.rand()`) длинной 100. Преобразуйте его так, чтобы
* Максимальный элемент(ы) был равен 1
* Минимальный элемент(ы) был равен 0
* Остальные элементы в итнтервале от 0 до 1 остаются прежними

In [6]:
# my_array = np.array([np.random.rand() for _ in range(100)]) ## Your code here
my_array = np.random.sample(100)
my_array[my_array == np.max(my_array)] = 1
my_array[my_array == np.min(my_array)] = 0

print(np.max(my_array), np.min(my_array))
print(my_array)

1.0 0.0
[0.26955715 0.02525827 0.1918833  0.75581971 1.         0.6655359
 0.97159595 0.29301412 0.75958137 0.34795742 0.42471545 0.90419599
 0.80405074 0.58544927 0.8384113  0.72942965 0.58813137 0.92548171
 0.49308803 0.29621729 0.36505529 0.26222725 0.01754279 0.18628923
 0.37109492 0.97999086 0.18694095 0.17493164 0.39702191 0.07910515
 0.29619296 0.9240746  0.1777887  0.4833689  0.20637625 0.6916913
 0.         0.82980192 0.55306158 0.03577645 0.52055398 0.70066211
 0.4402336  0.72148254 0.38610267 0.64593285 0.11130262 0.82404955
 0.38411    0.27914876 0.85317903 0.70696564 0.04797867 0.32407936
 0.08169078 0.94444675 0.69356429 0.47050468 0.70791357 0.84497791
 0.71718874 0.43047069 0.56069315 0.9598422  0.34046489 0.48120762
 0.69206099 0.45604328 0.46576647 0.41275421 0.97336457 0.76266042
 0.15652943 0.93157393 0.9226055  0.91081291 0.30000133 0.92607913
 0.70972594 0.70589259 0.70240539 0.73401432 0.63616192 0.60302287
 0.58875875 0.61767757 0.15102616 0.70921625 0.27055557 

Создайте array размером $5 \times 6$ с целыми числами в интервале [0,50]. Напечатайте колонку, которая содержит максимальный элемент полученной матрицы 

In [7]:
my_array = np.random.randint(0, 50, (5, 6)) ## Your code here
selected_column = my_array[:, np.unravel_index(my_array.argmax(), my_array.shape)[1]] ## Your code here
print('Shape: ',my_array.shape)
print('Array')
print(my_array)
print(selected_column)

Shape:  (5, 6)
Array
[[36 48  9 17  5 24]
 [18 10 43 28  0  4]
 [33 10 37  3 11 47]
 [32 19 32 14 29 43]
 [26 49  2 34 32 29]]
[48 10 10 19 49]


Напишите функцию, которая принимает на вход матрицу (array) X и возвращает все её уникальные строки в виде новой матрицы.

In [14]:
def get_unique_rows(X):
    # Your code here
    X_unique = np.unique(X, axis=0)
    return X_unique

In [15]:
X = np.random.randint(4, 6, size=(10,3))
print(X)

[[5 4 5]
 [4 4 5]
 [4 5 5]
 [4 4 5]
 [5 5 4]
 [4 5 4]
 [4 4 5]
 [5 5 5]
 [5 4 5]
 [5 5 5]]


In [16]:
get_unique_rows(X)

array([[4, 4, 5],
       [4, 5, 4],
       [4, 5, 5],
       [5, 4, 5],
       [5, 5, 4],
       [5, 5, 5]])